apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: tinyhouse.dev
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: tinyhouse-server-svc
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: tinyhouse-client-svc
              servicePort: 3000
