version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app/client/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/app/server/"
    schedule:
      interval: "daily"      
