version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app/client/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/app/server/"
    schedule:
      interval: "daily"     
  - package-ecosystem: "docker"
    directory: "/app/client/"
    schedule:
      interval: "daily"      
  - package-ecosystem: "docker"
    directory: "/app/server/"
    schedule:
      interval: "daily"  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
