apiVersion: skaffold/v2beta10
kind: Config
deploy:
  kubectl:
    manifests:
      - ../k8s/*
build:
  local:
    push: true
  artifacts:
    - image: webmakaka/tinyhouse-client-app2
      context: ../app/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts*'
            dest: .
    - image: webmakaka/tinyhouse-server-app2
      context: ../app/server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts*'
            dest: .
